// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/ghaidafasya24",
            "email": "714220031@std.ulbi.ac.id"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/restoran": {
            "get": {
                "description": "Mengambil semua data menu.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Get All Data Menu.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Menu"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.BahanBaku": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string"
                },
                "bahan_baku": {
                    "type": "string"
                },
                "jumlah": {
                    "type": "string"
                }
            }
        },
        "controller.Kategori": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string"
                },
                "kategori": {
                    "type": "string"
                }
            }
        },
        "controller.Menu": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string"
                },
                "bahan_baku": {
                    "$ref": "#/definitions/controller.BahanBaku"
                },
                "deskripsi": {
                    "type": "string"
                },
                "harga": {
                    "type": "number"
                },
                "kategori": {
                    "$ref": "#/definitions/controller.Kategori"
                },
                "nama": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "bp-tubes-c48fa88ca6a5.herokuapp.com",
	BasePath:         "/",
	Schemes:          []string{"https", "http"},
	Title:            "TES SWAGGER ULBI",
	Description:      "This is a sample swagger for Fiber",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
