basePath: /
host: bp-tubes-c48fa88ca6a5.herokuapp.com
info:
  contact:
    email: 714220031@std.ulbi.ac.id
    name: API Support
    url: https://github.com/ghaidafasya24
  description: This is a sample swagger for Fiber
  title: TES SWAGGER ULBI
  version: "1.0"
paths: {}
schemes:
- https
- http
swagger: "2.0"
