basePath: /
definitions:
  controller.BahanBaku:
    properties:
      _id:
        type: string
      bahan_baku:
        type: string
      jumlah:
        type: string
    type: object
  controller.Kategori:
    properties:
      _id:
        type: string
      kategori:
        type: string
    type: object
  controller.Menu:
    properties:
      _id:
        type: string
      bahan_baku:
        $ref: '#/definitions/controller.BahanBaku'
      deskripsi:
        type: string
      harga:
        type: number
      kategori:
        $ref: '#/definitions/controller.Kategori'
      nama:
        type: string
    type: object
host: bp-tubes-c48fa88ca6a5.herokuapp.com
info:
  contact:
    email: 714220031@std.ulbi.ac.id
    name: API Support
    url: https://github.com/ghaidafasya24
  description: This is a sample swagger for Fiber
  title: TES SWAGGER ULBI
  version: "1.0"
paths:
  /insert:
    post:
      consumes:
      - application/json
      description: Input data menu.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Menu'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data menu.
      tags:
      - Menu
  /restoran:
    get:
      consumes:
      - application/json
      description: Mengambil semua data menu.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Menu'
      summary: Get All Data Menu.
      tags:
      - Menu
  /restoran/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data menu.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Menu'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Menu.
      tags:
      - Menu
schemes:
- https
- http
swagger: "2.0"
